### ISSUE TITLE
Incorrect project description

### ISSUE THREAD

**Issue by tarikjn** [crocodilejs/frisbee#18]
The project description reads: 

> Stripe-inspired API wrapper around ES6/ES7's fetch() method

but `fetch` is a WHATWG browser API spec, not an ES6/7 feature.

**Comment by niftylettuce** [comment]
Fixed this, see 1.1.9.

**Comment by aretecode** [comment]
https://github.com/joinspontaneous/frisbee/commit/4f4e5ed28f70627972e2c188be2ee6fd293d2b4e
