### ISSUE TITLE
Incorrectly describes Fetch as part of ES

### ISSUE THREAD

**Issue by jmm** [crocodilejs/frisbee#24]
This says in several places (in the README, on npm) that fetch is part of ECMAScript (6, or 7) but that's not correct. It's defined by a [WHATWG spec](https://fetch.spec.whatwg.org/). This in particular doesn't make sense:

> **Why don't you have an ES5 compiled version readily available in this git repo?**
> As this module relies on ES6 **fetch**, there is currently no backwards compatibility for ES5
- Availability of fetch has little to do with ES version support, except for Promise, which can be polyfilled in ES5.
- The expectation would likely be for an ES5 version on npm, not in the source repo.

**Comment by niftylettuce** [comment]
my apologies I was working on several projects at once haha, will fix this

**Comment by aretecode** [comment]
https://github.com/crocodilejs/frisbee/issues/18

**Comment by niftylettuce** [comment]
Fixed this, see 1.1.9.

**Comment by aretecode** [comment]
https://github.com/joinspontaneous/frisbee/commit/4f4e5ed28f70627972e2c188be2ee6fd293d2b4e
