### ISSUE TITLE
Add querystring 

### ISSUE THREAD

**Issue by davidbq** [crocodilejs/frisbee#37]
Hi guys, can someone explain me how to add a querystring to my request? Reading the documentation it says I can do it but I haven't found the way to do it.

Imagine my `baseURI` is: `https://mybaseuri.com/ `
My service is: `users`
And I want to add: userId=0209206245902063 

So it should look like `https://mybaseuri.com/users?userId=0209206245902063`

An example would be really appreciated. Thanks in advance.

**Comment by niftylettuce** [comment]
Just specify it as the body, e.g. if you want `?foo=bar&baz=beep`:

api.get('/baz-beep', { body: { foo: 'bar', baz: 'beep' } });

💥

**Comment by niftylettuce** [comment]
@davidbq here's the relevant code from the source that does this magic for you 🎉 

https://github.com/crocodilejs/frisbee/blob/master/src/frisbee.js#L155-L157

**Comment by davidbq** [comment]
Awesome!!!
Thanks a lot.
